# Theme settings/
remote_theme: jekyll/minima
#pages-themes/minimal@v0.2.0 
plugins:
  - jekyll-remote-theme 

# Navigation links for your portfolio
header_pages:
  - /results/work-ive-done
  - /results/daily-journal

# Build settings
markdown: kramdown
