# Site settings
title: Abdullahi Mohamed's Portfolio
description: "Full-Stack Developer portfolio showcasing projects, skills, and expertise in web and software development, with a focus on modern technologies, clean code, and practical solutions."

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0 
plugins:
  - jekyll-remote-theme 

# Navigation links for your portfolio
header_pages:
  - index.md
  - projects.md
  - about.md

# Build settings
markdown: kramdown
