# Site settings
title: My Work Log
description: "This is what I am working on at any given time. I will update this with my progress and the reports as often as I can."

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0 
plugins:
  - jekyll-remote-theme 

# Navigation links for your portfolio
header_pages:
  - /results/work_ive_done.md
  - /results/daily_journal.md

# Build settings
markdown: kramdown
